version: '3.8'

services:
  vote:
    build: ./vote
    ports:
      - "5000:80"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

  result:
    build: ./result
    ports:
      - "5001:80"
    depends_on:
      - db

  redis:
    image: redis:alpine

  worker:
    build: ./worker
    depends_on:
      - redis
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: votes
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
