version: '3.8'

services:
  flask1:
    build: ./flask_app
    networks:
      - app_net

  flask2:
    build: ./flask_app
    networks:
      - app_net

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - flask1
      - flask2
    networks:
      - app_net

networks:
  app_net:
